### ISSUE TITLE
Athena database creation

### ISSUE THREAD

**Issue by andrewcstewart** [dataops-tk/target-athena#11]
https://docs.aws.amazon.com/athena/latest/ug/creating-databases.html

Open question here.  Normally db creation seems to be handled outside of targets.  It could make sense for this target to just create a db though.

**Comment by aaronsteers** [comment]
This should be working: https://github.com/dataops-tk/target-athena/commit/c0a6c3d64609478f488279775a32f0316bc9b264

Let me know if you find otherwise. 👍

**Comment by aaronsteers** [comment]
Also, per the documentation [here](https://docs.aws.amazon.com/athena/latest/ug/create-database.html), schemas and databases are apparently basically the same thing in athena-land.

> ## CREATE DATABASE
> 
> Creates a database. The use of DATABASE and SCHEMA is interchangeable. They mean the same thing.
